### ISSUE TITLE
Naomi breaks syntax highlighting for LaTeX and MarkdownEditing

### ISSUE THREAD

**Issue by hsiktas** [borela/naomi#117]
Hi,

as soon as I enable the Naomi package I get bombarded by multiple error windows like this and the corresponding syntax highlightings stop working:

![image](https://user-images.githubusercontent.com/4571159/38060167-db70079c-32e9-11e8-8d13-d62e83f50213.png)
![image](https://user-images.githubusercontent.com/4571159/38060179-e8714aa0-32e9-11e8-933c-42d21e012989.png)

In order to get back syntax highlighting for LaTeX and Markdown files I have to disable the Naomi package.
Unfortunately, I could not find any additional information in the Sublime Text Console. :(

**Comment by borela** [comment]
I believe I found the error to be related to styled components or template strings. Do you have a sample of a working Latex code that have embedded javascript?

**Comment by hsiktas** [comment]
Sorry I have never used embedded JavaScript in my LaTeX files. Do you believe that this happens only when we embed JS into the other syntaxes?

**Comment by borela** [comment]
This bug was puzzling, the only time I was able to reproduce it was in a dev build I used on a friend's PC, I use the 3143 and the recursion bug does not happen there, so it's a regression in dev build.

**Comment by borela** [comment]
I recommend posting an issue here https://github.com/sublimehq/Packages/issues I don't use the dev builds so I can't say for sure but from looking at the current syntax there for LaTeX, my guess would be that the new embed action is causing the issue.

**Comment by deathaxe** [comment]
These error messages normally tell you some scopes not being popped off correctly, causing the scope stack to be flooded. To prevent overflow and app crash no more than 25000 levels are allowed. I realized these issues several times during developing my CNC syntaxes.

An example of code which causes issues might be helpful for detailed debugging.

It's not quite obvious how `MarkdownEditing` and `LaTeX` which seem to trigger the error are associated with `Naomi`. Opening several .md files didn't cause such issues here.

Disabling MardownEditing and opening a .md file using Naomi's syntax seemed not to highlight anything at all. 

_The .md was a readme created by create-react-app. It's quite long._

Without detailed info about the combination of languages triggering the issue I guess it will be hard to find the culprit. I guess if `lang1` includes `lang2` and `lang2` includes `lang1` for some reason, a recursion could quickly arise.

**Comment by borela** [comment]
@deathaxe Most of the contexts pop after matching, the biggest issue is that it does not happen in the build 3143, the LaTeX works, embedded javascript uses the Naomi's version as expected.

This is what puzzled me for a while, I don't use the dev builds, when I got to a computer with it, all I need to do for the error to appear is select the LaTeX syntax.

**Comment by borela** [comment]
@deathaxe Another option that could be added to the core, is a option to print the trace of the supposed recursion.

**Comment by deathaxe** [comment]
The initial post doesn't state anything about LaTeX with embedded JavaScript but Markdown and a LaTeX file.

I actually opened a couple of LaTeX files and Markdowns with Naomi enabled on ST3160 without any issue.

As I am not a LaTeX expert I can't judge which constructs may trigger the issue. An example to reproduce might therefore help finding the culprit.

**Comment by deathaxe** [comment]
The culprit seems to be the _naomi.fjsx15.sublime-syntax_. 

## What I did

Step 1 - renaming one naomi syntax after another

Step 2 - commenting out some lines in  _syntaxes/naomi.fjsx15.sublime-syntax_

```
name: JavaScript
scope: source.js

file_extensions:
  - js
  - jsx
  - mjs

contexts:
  main:
    - match: ""
      push: [ meta, entry ]

  entry:
    - include: Packages/Naomi/syntaxes/fjsx15/comment.sublime-syntax
    # - include: Packages/Naomi/syntaxes/fjsx15/statement.sublime-syntax
    # - include: Packages/Naomi/syntaxes/fjsx15/expression.sublime-syntax

  meta:
    - meta_scope: meta.naomi
    - match: ""
      pop: true
```

Step 3 - following the comment breadcrumps via _syntaxes/fjsx15/comments.sublime-syntax_ to _syntaxes/flow1/comments.sublime-syntax_

Step 4 - commenting out all the includes within _syntaxes/flow1/comments.sublime-syntax_

```
hidden: true
scope: ...

contexts:
  main:
    - match: "/\\*\\s*::"
      scope: punctuation.definition.comment.begin.flow
      set: block-end
    - match: /\*(?=\s*:)
      scope: punctuation.definition.comment.begin.flow
      set: block-end

  block-end:
    - meta_scope: comment.block.flow
    - match: \*/
      scope: punctuation.definition.comment.end.js.fjsx15
      pop: true
    - match: (?=\S)
      push: type-statement-or-expression

  type-statement-or-expression:
    - match: (;)
      captures:
        1: keyword.other.terminator.flow
      pop: true
    # - include: Packages/Naomi/syntaxes/flow1/associated-type.sublime-syntax
    # - include: Packages/Naomi/syntaxes/flow1/declare.sublime-syntax
    # - include: Packages/Naomi/syntaxes/flow1/interface.sublime-syntax
    # - include: Packages/Naomi/syntaxes/flow1/type-aliasing.sublime-syntax
    # - include: Packages/Naomi/syntaxes/fjsx15/class/property.sublime-syntax
    # - include: Packages/Naomi/syntaxes/flow1/indexer.sublime-syntax
    # - include: Packages/Naomi/syntaxes/fjsx15/import.sublime-syntax
    # - include: Packages/Naomi/syntaxes/fjsx15/export.sublime-syntax
```

Step 5 No more errors.


## Alternative

Moving the includes out of the `entry` into `main` works as well.

```
name: JavaScript
scope: source.js

file_extensions:
  - js
  - jsx
  - mjs

contexts:
  main:
    - include: Packages/Naomi/syntaxes/fjsx15/comment.sublime-syntax
    - include: Packages/Naomi/syntaxes/fjsx15/statement.sublime-syntax
    - include: Packages/Naomi/syntaxes/fjsx15/expression.sublime-syntax
    # - match: ""
    #   push: [ meta, entry ]

  # entry:

  meta:
    - meta_scope: meta.naomi
    - match: ""
      pop: true
```


## Conclustion

There is at least one pop too much or too less somewhere.

Despite the fact your file structure is "unique" compared to all the other syntax projects, I am not sure whether the pop statements always work as you seem to expect them to do. 

1. I find it weird to expect a pop statement located in a `main` of a syntax-definition to pop off the whole syntax definition (as used in some of the included files). IMHO `main` is the top-level of a syntax file and therefore shouldn't be popped off stack.

2. All the pushes from your `main` scopes seem strange as well. I'd expect the risk to fail a correct pop from stack to be very high by design in this package. At least for me its very hard to follow from file to file. I'd pass the question to one of the devs @wbond or @jps but I feel like ST's syntax infrastructure was never meant to be used this way, even though your modular approach is very interesting from a point of developer. 

Hope it doesn't sound too negative! 

As the risk of popping one stack-level too much or too less is very high, I honestly doubt the core to be blamed. As more and more syntaxes embed others the risk of stack overflow increases if at least one of them doesn't handle stack push/pop correclty. Popping off a level too much or less can cause more troubles then. I had to struggle with such issues, too, when embedding some of my CNC languages into others.

**Comment by borela** [comment]
@deathaxe Yesterday I went to a friend's house to test the patches you showed as he uses the dev build(I can't test it on my machines right now, too many projects openned).

None of the patches worked, what is even stranger is that the bug seams random, often times I would comment parts of the syntax and it would be ok, but then if I tried just adding a dummy context, for example:

```
some-unused-context:
  - match: test
    scope: test
```

The bug would come back. It looks like a hard limit on the number of contexts or files involved when the embed feature is used, but I can't say for sure because the place that caused the bug would change from time to time (which I am guessing is a result of listing the files as the OS (Windows at least) does not garantee the files to be listed alphabetically).

**Comment by deathaxe** [comment]
> suggested the stack trace because recursion bugs are always hard to track

I agree with a function to help tracing such issues would help very much.

> the bug seams random

I had same experiences yesterday. I first commented out the `source.shell` stuff from LaTeX and everything seemed working well. A step further it didn't.

But this is what I experienced in the past, too, when I added some unbalanced push/pops into my files. It seemed to work for smaller files, but when they got too big, I hit the sanity limit.

What I can see here feels exactly like that. 

### 3143 vs. 3160

Loading my example1.tex to 3143 takes quite long to load. It feels like 3160 just gives up more quickly just like the sanity limit was recently added. ST3143 even got unresponsive once, when loading the file for the very first time.

Using the LaTeX package from 3143 in 3160 fails, too. So this issue is related to a change in core (added sanity limit?).

Not sure whether it is related, but I can see a couple of issues in 3143's console. Maybe they give some hints about possible reasons. Unreachable sections in a syntax file feel not too ideal. 

```
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#13c4e162771b843d63c0bb268a8373dc::16d7f8c69dc5d9bad0df65b3e033ccbb::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule scope:text.html.markdown#main has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#16d7f8c69dc5d9bad0df65b3e033ccbb::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#13c4e162771b843d63c0bb268a8373dc::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#da722399f83b5d5ce019cca5f4a14d31::16d7f8c69dc5d9bad0df65b3e033ccbb::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax##anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#20893eebc5cc3ea617f6d7708fbf253a::16d7f8c69dc5d9bad0df65b3e033ccbb::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#da722399f83b5d5ce019cca5f4a14d31::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#20893eebc5cc3ea617f6d7708fbf253a::#anon_main_0 has a scope name, but is unreachable, so the name will never be used

rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#13c4e162771b843d63c0bb268a8373dc::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax##anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#da722399f83b5d5ce019cca5f4a14d31::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
rule Packages/Naomi/syntaxes/fjsx15/literal/string/template.sublime-syntax#20893eebc5cc3ea617f6d7708fbf253a::#anon_main_0 has a scope name, but is unreachable, so the name will never be used
```

### About embed

The LaTeX in 3143 embeds syntaxes like this

```
        - match: '(\{)(javascript|js)(\})'
          captures:
            1: punctuation.definition.group.brace.begin.latex
            2: variable.parameter.function.latex
            3: punctuation.definition.group.brace.end.latex
          push:
            - meta_include_prototype: false
            - meta_content_scope: meta.environment.embedded.js.latex source.js.embedded
            - match: '(?=\\end\{minted\})'
              pop: true
            - include: scope:source.js
```

The `embed` statement in 315x+ is basically a more comprehensive replacement for

```
        - match: '(\{)(javascript|js)(\})'
          captures:
            1: punctuation.definition.group.brace.begin.latex
            2: variable.parameter.function.latex
            3: punctuation.definition.group.brace.end.latex
          push:
            - meta_include_prototype: false
            - meta_content_scope: meta.environment.embedded.js.latex source.js.embedded
            - include: scope:source.js
          with_prototype:
            - match: '(?=\\end\{minted\})'
              pop: true
```

The major difference between both is the `with_prototype` structure, what is basically the `escape` can be compared to, even though it can do a little bit more.

I don't find related issues in https://github.com/SublimeTextIssues/Core/issues at the moment, but I think I can remember an issue with `with_prototype` not being handled by `main` sections the same way like with other sections in a syntax file, which might cause the issue without knowing/seeing as it is not obvious.

If I were you, I'd try to avoid including a whole syntax (including the `main` ) like

```
    - include: Packages/Naomi/syntaxes/fjsx15/comment.sublime-syntax
```

but rather include the stuff in dedicated sections like

```
    - include: Packages/Naomi/syntaxes/fjsx15.sublime-syntax#comment
```

This is what I did successfully in the past, when I intended to share some rules. This is what PackageDev does successfully, too.
