### ISSUE TITLE
CSS Syntax Parsing

### ISSUE THREAD

**Issue by Cherry** [borela/naomi#155]
I've found a couple CSS syntax parsing issues.

Escaped data attributes:
```css
body.javascriptDisabled [ng\:cloak],
body.javascriptDisabled [ng-cloak],
body.javascriptDisabled [data-ng-cloak],
body.javascriptDisabled [x-ng-cloak],
body.javascriptDisabled .ng-cloak,
body.javascriptDisabled .x-ng-cloak {
	display: initial !important;
}
```
![](https://up.jross.me/kplxt)

PostCSS Import (as per https://github.com/csstools/postcss-normalize):
```css
@import-normalize;

*,
*::after,
*::before {
	box-sizing: border-box;
}
```
![](https://up.jross.me/hqu86)
